# Site settings (baseurl must end with a trailing slash!)
baseurl = "https://www.mattstratton.com/"
languageCode = "en-us"
title = "Matt Stratton"
theme = "mattstrattondotcom"

googleAnalytics = "UA-7327719-1"

# The theme uses pagination for post, gallery, and project listings.
paginate = 12

# The theme supports disqus, which will appear only on deployed sites,
# not locally when run with `hugo server`; as with standard Hugo disqus,
# you can specify disqus_identifier, disqus_title, and disqus_url in the
# front matter of specific content.
disqusShortname = "mattstratton"

[permalinks]
	page = "/:filename/"
	about = "/:filename/"
    speaking = "/:filename/"

# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# SectionPagesMenu = "Main"
# About section of menu
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "Speaking"
    identifier = "speaking"
    url = "/speaking"

[[Menu.Main]]
    name = "Blog"
    identifier = "blog"
    url = "/post"
# [[Menu.Main]]
#     name = "Contact"
#     identifier = "contact"
#     url = "/contact"

[[Menu.Main]]
    name = "Newsletter"
    identifier = "newsletter"
    url = "/newsletter"

[params]
    copyright_notice = "Copyright &#169; 2001-2018 [Matt Stratton](https://www.mattstratton.com)"


  [params.social]
    github = "mattstratton"
    gitlab = "mattstratton"
    facebook = "matt.stratton"
    twitter = "mattstratton"
    twitter_domain = "mattstratton.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    pinterest = "mattstratton"
    instagram = "mattstratton"
    youtube = "mattstratton"
    linkedin = "matt.stratton"

 
