baseURL: "https://www.mattstratton.com/"
languageCode: "en-us"
title: "Matty Stratton"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
googleAnalytics: G-7CPY8D750K

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /post
      weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    - identifier: speaking
      name: Speaking
      title: speaking
      url: https://speaking.mattstratton.com
      weight: 2
    - identifier: podcast
      name: Podcast
      title: podcast
      url: https://arresteddevops.com
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Matty Stratton"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Matty Stratton" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Matty."
    subtitle: "Developer Relations leader and community builder"
    content: "A seasoned leader in Developer Relations, I'm dedicated to unlocking the potential of developer communities and transforming that energy into tangible business outcomes."
    image: /img/goto.jpg
    bottomImage:
      enable: false
    roundImage: false # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/Matty-Stratton-CV-2024.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/mattstratton
        - icon: fab fa-x-twitter
          url: https://twitter.com/mattstratton
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/img/matty-shades-500-sq.png"
    content: |-
      As a seasoned leader in Developer Relations, I'm dedicated to unlocking the potential of developer communities and transforming that energy into tangible business outcomes.

      My background blends technical expertise with strategic vision, enabling me to build and lead high-impact DevRel teams that serve as the bridge between technology companies and the developer communities they rely on.

      My approach centers on understanding developers' needs and challenges, creating resources and tools that empower them to achieve their best work, and nurturing a community where knowledge and support flow freely. By aligning developer success with business objectives, I've helped companies cultivate loyalty, spur innovation, and enter new markets.

      A recognized industry and community expert, I've delivered keynotes at industry conferences, contributed to influential tech publications, and hosted podcasts that delve into the heart of developer relations and tech community building.

    skills:
      enable: true
      title: "Skills/Expertise"
      items:
        - "Kubernetes"
        - "DevOps"
        - "Product-Led Growth"
        - "Developer Relations"
        - "Infrastructure as Code"
        - "Developer Marketing"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Director, Developer Relations and Growth"
        company: "Aiven"
        companyUrl: "https://aiven.io"
        date: "2022 - 2024"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
        content: |
          - Led global team of developer advocates, educators, community program managers, and growth specialists<br>
          - Launched online developer workshops program to drive user account signup
          - Implemented comprehensive metrics program, including trackable CTAs and DevRel Qualified Leads to measure impact of activities on both user growth and account influence
          - Collaborated with GTM and sales team to expand usage of Aiven within existing accounts
          - Built PLG-focused motion on direct adoption of the Aiven platform, including self-service accounts as well as Product Qualified Leads handed-off to sales team
          - Responsible for Self-Service Revenue targets for Direct Adoption

      - job: "Staff Developer Advocate"
        company: "Pulumi"
        companyUrl: "https://www.pulumi.com/"
        date: "2021 - 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          - Keynote speaker at industry and community conferences on the topics of DevOps, Infrastructure as Code, and Cloud Engineering principles.
          - Created and launched “Puluminaries” community champion program to recognize and build advocates in the Pulumi user community.
          - Engage cross-functionally with the Marketing organization to align community needs/voice with product marketing messaging and initiatives.
          - Developed community measurement program to correlate developer advocate actions to community growth, using the Orbit Model.
          - Defined concepts and pillars of the Cloud Engineering approach for Pulumi users as well as the larger industry community. 

      - job: "Transformation Specialist, NAPS Transformation Office"
        company: "Red Hat"
        companyUrl: "https://www.redhat.com/"
        date: "2020 - 2021"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Responsible for building strategic relationships with executives and key leaders to promote and sell Red Hat's portfolio of emerging tech products, including cloud, PaaS (OpenShift powered by Kubernetes and Docker), mobile, application development, application and service hosting, business rules management, business process management, content aggregation, data federation, and service integration on-prem or in the cloud.
          - Engage as a trusted advisor with senior technology leadership in State/Local public sector agencies around cultural transformation
          - Created “Five Elements Assessment” pre-sales tool to drive close of transformational services engagements
          - Represent Public Sector Transformation Office at government-focused conferences and panels

      - job: "Senior Developer Advocate"
        company: "PagerDuty"
        companyUrl: "https://pagerduty.com"
        date: "2017 - 2020"
        info:
          enable: false
        content: |
          - Spoke at industry events worldwide on the topics of DevOps, HumanOps, and others to drive PagerDuty’s values and principles to the larger community
          - Authored open-sourced Ops Guides for sharing practices around Incident Response, Operational Reviews, and more
          - Focused on results-oriented metrics and measurement of the effectiveness of the Community and Advocacy team
          - Met with senior IT leadership at PagerDuty customers and prospects to help share knowledge of good practices around digital transformation and DevOps
          - Created and maintained the PagerDuty “Breakathon” event, including infrastructure development, content creation, and event management
          - Mentored other members of the Community team on event speaking, industry practices, and content creation
          - Worked closely with other groups in the PagerDuty organization, including Product, Marketing, and Sales, to provide a voice of the community

      - job: "Senior Solutions Architect"
        company: "Chef"
        companyUrl: "https://chef.io"
        date: "2014 - 2017"
        content: ""
        info:
          enable: false

      - job: "Managing Consultant"
        company: "10th Magnitude"
        # companyUrl: "https://pagerduty.com"
        date: "2013 - 2014"
        info:
          enable: false
        content: |
          Led the 10th Magnitude practice for Infrastructure as a Service (IaaS), Infrastructure Automation, and DevOps consulting engagements. Work with clients to leverage cutting-edge optimization techniques, tools, and concepts to streamline delivery, eliminate waste, and increase velocity. 

      - job: "Director, Technology Operations"
        company: "Apartments.com"
        company_slug: "apartments"
        # companyUrl: "https://pagerduty.com"
        date: "2007 - 2013"
        info:
          enable: false
        content: ""

  # Education
  education:
    enable: false
    # title: "Custom Name"
    # index: false
    # items:
    #   - title: "Master of Business Administration"
    #     school:
    #       name: "University of California, Berkeley"
    #       url: "https://example.org"
    #     date: "2013 - 2015"
    #     GPA: "3.8 out of 5.0"
    #     content: |-
    #       Extracurricular Activities
    #         - Lorem ipsum dolor sit amet consectetur adipisicing elit.
    #         - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
    #   - title: "Bachelor of Science in Computer Science"
    #     school:
    #       name: "Massachusetts Institute of Technology"
    #       url: "https://example.org"
    #     date: "2009 - 2013"
    #     GPA: "3.9 out of 5.0"
    #     content: |-
    #       I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
    #       - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
    #       - Face mask detection using a single convolutional neural network.

    #       Extracurricular Activities
    #         - Lorem ipsum dolor sit amet consectetur adipisicing elit.
    #         - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
    #     featuredLink:
    #       enable: true
    #       name: "My academic record"
    #       url: "https://example.com"
    #   - title: "High School"
    #     school:
    #       name: "Thomas Jefferson High School for Science and Technology."
    #       url: "https://example.org"
    #     GPA: "4.2 out of 5.0"
    #     featuredLink:
    #       enable: true
    #       url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    title: "Publications"
    items:
      - title: Organizational Patterns - A Developer Portal
        content: pulumi.com
        url: https://www.pulumi.com/blog/organizational-patterns-developer-portal/
        image: https://www.pulumi.com/blog/organizational-patterns-developer-portal/meta.png
      - title: The Four Agreements of Incident Response
        content: pagerduty.com
        url: https://www.pagerduty.com/blog/four-agreements-incident-response/
        image: /img/publications/four-agreements.png
      - title: A Brief DevOps History - Databases to Infinity and Beyond
        content: The New Stack
        url: https://thenewstack.io/a-brief-devops-history-databases-to-infinity-and-beyond/
        image: /img/publications/database-history.jpg
      # - title: Hugo Profile
      #   content: Developed a theme and getting 1K+ downloads per month.
      #   url: "https://github.com/gurusabarish/hugo-profile"
      #   image: /images/achievment.jpg
      # - title: Microsoft Imagine Runner
      #   content: We are developed a product which can help others.
      # - title: Google Summer of Code
      #   content: Contributed to a open source project.
      #   url: https://example.com

  # projects
  projects:
    enable: true
    title: "Public Speaking"
    items:
      # - title: Hugo Profile
      #   content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
      #   image: /images/projects/profile.png
      #   featured:
      #     name: Demo
      #     link: https://hugo-profile.netlify.app
      #   badges:
      #     - "Hugo"
      #     - "Bootstrap"
      #     - "Javascript"
      #   links:
      #     - icon: fa fa-envelope
      #       url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/hugo-profile
      #     - icon: fab fa-twitter
      #       url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      # - title: Image Converter
      #   content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
      #   image: /images/projects/converter.jpg
      #   featured:
      #     name: Demo
      #     link: https://django-converter.herokuapp.com
      #   badges:
      #     - "Django"
      #     - "Bootstrap"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/converter

      # - title: Hugo Profile V2
      #   content: A clean and simple Hugo template for personal portfolio and blog.
      #   image: /images/projects/profile2.jpg
      #   featured:
      #     name: Demo V2
      #     link: https://hugo-profile-2.netlify.app
      #   badges:
      #     - "Hugo"
      #     - "Bootstrap"
      #     - "Javascript"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:matt.stratton@gmail.com
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: mzzbbdqj # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"
      messageRows: 5

  footer:
    recentPosts:
      path: "post"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/mattstratton
      linkedin: https://www.linkedin.com/in/mattstratton/
      twitter: https://twitter.com/mattstratton
      instagram: https://instagram.com/mattstratton

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "Copyright 2001-2024 Matty Stratton"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
