# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
 command = "bin/netlify-production.sh"
 publish = "public/"
 
 [context.deploy-preview]
  command = "bin/netlify.sh"
  publish = "public/"
 
[context.production.environment]
   HUGO_VERSION = "0.135.0"
   
[context.deploy-preview.environment]
  HUGO_VERSION = "0.135.0"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.135.0"
