import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import manifest from '../data/slide-text.json';

// Extracted slide text lives alongside each committed deck at
// public/slides/{notistId}.txt (generated by scripts/slide-text.ts). The
// manifest records word counts for cheap presence checks; the full text is read
// from disk at build time and folded into the deep search index.
const SLIDES_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '../../public/slides');

const counts = manifest as Record<string, { words: number }>;

export function hasSlideText(notistId: string): boolean {
  return notistId in counts;
}

export function slideTextWords(notistId: string): number {
  return counts[notistId]?.words ?? 0;
}

/** Extracted slide text for a deck, or null. */
export function readSlideText(notistId: string): string | null {
  const path = resolve(SLIDES_DIR, `${notistId}.txt`);
  return existsSync(path) ? readFileSync(path, 'utf8').trim() : null;
}
