import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import manifest from '../data/transcripts.json';

// Committed transcripts live in public/transcripts/{notistId}.txt — one cleaned,
// readable transcript per talk that has captions. The manifest (generated by
// scripts/transcripts.ts) records word counts so pages/search can check presence
// cheaply; the full text is read from disk at build time (SSG, Node available).
const TRANSCRIPT_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '../../public/transcripts');

const counts = manifest as Record<string, { words: number; cleaned?: true }>;

export function hasTranscript(notistId: string): boolean {
  return notistId in counts;
}

/** True once transcript-cleanup has produced a readable, edited version. */
export function isCleaned(notistId: string): boolean {
  return counts[notistId]?.cleaned === true;
}

export function transcriptWords(notistId: string): number {
  return counts[notistId]?.words ?? 0;
}

/** Cleaned transcript text (newline-separated caption lines), or null. */
export function readTranscript(notistId: string): string | null {
  const path = resolve(TRANSCRIPT_DIR, `${notistId}.txt`);
  return existsSync(path) ? readFileSync(path, 'utf8').trim() : null;
}

/**
 * Group transcript text into readable paragraphs. Cleaned transcripts already
 * have real paragraphs separated by a blank line — split on those. Raw caption
 * transcripts have no structure, so fall back to grouping `perPara` lines.
 */
export function toParagraphs(text: string, perPara = 8): string[] {
  if (/\n\s*\n/.test(text)) {
    return text.split(/\n\s*\n/).map((p) => p.replace(/\s+/g, ' ').trim()).filter(Boolean);
  }
  const lines = text.split('\n').filter(Boolean);
  const paras: string[] = [];
  for (let i = 0; i < lines.length; i += perPara) {
    paras.push(lines.slice(i, i + perPara).join(' '));
  }
  return paras;
}
