import { defineCollection, reference, z } from 'astro:content';
import { glob } from 'astro/loaders';

// Preserve the exact filename as the entry id. The glob loader slugifies
// (lowercases) ids by default, which breaks Notist's case-sensitive base62 ids
// (e.g. "xsgHui" -> "xsghui") so event references stop resolving.
const verbatimId = ({ entry }: { entry: string }) => entry.replace(/\.md$/, '');

// One entry per *delivery* of a talk (matching Notist's model: the same abstract
// given at three events is three records). Generated by scripts/ingest.ts; the
// `video`/`resources`/slide fields are populated from live Notist data.
const talks = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/talks', generateId: verbatimId }),
  schema: z.object({
    notistId: z.string(), // e.g. "w7YksW" — drives the URL
    title: z.string(),
    // NOT named `slug`: Astro's glob loader treats a `slug` field as the entry id,
    // and the same talk given at multiple events shares one Notist slug — which
    // would collide. The unique entry id comes from the filename (= notistId).
    notistSlug: z.string(), // last path segment of Notist links.self; the URL slug
    presentedOn: z.coerce.date(),
    publishedOn: z.coerce.date().optional(),
    timezone: z.string().optional(),
    event: reference('events').optional(),
    abstractHtml: z.string().optional(),
    // Slides: 'pdf' = committed PDF rasterized at build; 'images' = Notist
    // pre-rendered images downloaded at ingest; 'none' = no slides exist.
    slideSource: z.enum(['pdf', 'images', 'none']).default('none'),
    slidesPdf: z.string().nullable().default(null), // repo path to committed PDF
    slideImageCount: z.number().int().default(0),
    // Canonical video reference, resolved from the notist.ninja proxy at ingest.
    video: z
      .object({
        provider: z.enum(['youtube', 'vimeo']),
        id: z.string(),
      })
      .nullable()
      .default(null),
    resources: z
      .array(z.object({ title: z.string(), url: z.string().url() }))
      .default([]),
    thumbnail: z.string().nullable().default(null), // repo path, or null (21 talks)
  }),
});

// One per conference/event, deduplicated (93 unique across 106 talks).
const events = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/events', generateId: verbatimId }),
  schema: z.object({
    notistEventId: z.string(),
    name: z.string(),
    date: z.coerce.date().optional(),
    location: z.string().optional(),
    url: z.string().url().optional(),
    // Captured for a future "places I've spoken" map (issue #1). Not yet rendered.
    latitude: z.number().optional(),
    longitude: z.number().optional(),
  }),
});

export const collections = { talks, events };
